import BlogCard from "@/components/blog/blog-card";
import BlogHeader from "@/components/blog/blog-header";
import { Badge } from "@/components/ui/badge";
import { Input } from "@/components/ui/input";
import { allPosts } from "@/contentlayer/generated";
import { Link } from "@/i18n/navigation";

import { compareDesc } from "date-fns";
import { Metadata } from "next";
import { useLocale } from "next-intl";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function BlogPage() {
  const locale = useLocale();

  const posts = allPosts
    .filter((post) => post.published && post.locale === locale)
    .sort((a, b) => compareDesc(new Date(a.date), new Date(b.date)));

  const allTags = Array.from(
    new Set(posts.flatMap((post) => post.tags || []))
  ).sort();

  return (
    <div className="min-h-screen bg-gradient-to-br from-slate-50 to-white dark:from-slate-950 dark:to-slate-900">
      <div className="container mx-auto px-4 py-12">
        <BlogHeader />

        {/* Featured Post */}
        {posts.length > 0 && (
          <section className="mb-16">
            <div className="relative overflow-hidden rounded-2xl bg-gradient-to-r from-blue-600 to-purple-600 p-1">
              <div className="relative bg-white dark:bg-slate-900 rounded-xl p-8">
                <div className="flex items-center gap-2 mb-4">
                  <Badge variant="secondary">Featured</Badge>
                  <Badge variant="outline">
                    {posts[0].readingTime} min read
                  </Badge>
                </div>
                <h2 className="text-3xl font-bold mb-4 text-slate-900 dark:text-white">
                  {posts[0].title}
                </h2>
                <p className="text-lg text-slate-600 dark:text-slate-300 mb-6">
                  {posts[0].summary}
                </p>
                <div className="flex items-center justify-between">
                  <div className="text-sm text-slate-500 dark:text-slate-400">
                    {new Date(posts[0].date).toLocaleDateString("en-US", {
                      year: "numeric",
                      month: "long",
                      day: "numeric",
                    })}
                  </div>
                  <Link
                    href={posts[0].url}
                    className="inline-flex items-center px-6 py-3 rounded-lg bg-blue-600 text-white font-medium hover:bg-blue-700 transition-colors"
                  >
                    Read More →
                  </Link>
                </div>
              </div>
            </div>
          </section>
        )}

        {/* Filter Section */}
        <section className="mb-12">
          <div className="bg-white dark:bg-slate-800 rounded-2xl p-6 shadow-sm">
            <div className="flex flex-col sm:flex-row gap-4 items-center justify-between">
              <Input
                type="search"
                placeholder="Search articles..."
                className="max-w-sm"
              />
              <div className="flex flex-wrap gap-2">
                <Badge
                  variant="outline"
                  className="cursor-pointer hover:bg-slate-100 dark:hover:bg-slate-700"
                >
                  All
                </Badge>
                {allTags.slice(0, 6).map((tag) => (
                  <Badge
                    key={tag}
                    variant="outline"
                    className="cursor-pointer hover:bg-slate-100 dark:hover:bg-slate-700"
                  >
                    {tag}
                  </Badge>
                ))}
              </div>
            </div>
          </div>
        </section>

        {/* Blog Posts Grid */}
        <section>
          <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-8">
            {posts.slice(1).map((post) => (
              <BlogCard key={post._id} post={post} />
            ))}
          </div>

          {posts.length === 0 && (
            <div className="text-center py-16">
              <div className="text-6xl mb-4">📝</div>
              <h3 className="text-2xl font-semibold mb-2 text-slate-900 dark:text-white">
                No posts yet
              </h3>
              <p className="text-slate-600 dark:text-slate-400">
                Check back soon for new content!
              </p>
            </div>
          )}
        </section>
      </div>
    </div>
  );
}
